apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: deploy-task

spec:

  params:

    - name: APP_NAME
      type: string

  steps:

    - name: deploy
      image: quay.io/openshift/origin-cli:latest

      script: |
        #!/bin/sh
        set -e

        echo "========================================"
        echo "Starting Deployment"
        echo "========================================"

        echo ""
        echo "Application:"
        echo "$(params.APP_NAME)"

        echo ""
        echo "Current project:"
        oc project

        echo ""
        echo "Current image:"
        oc get deployment $(params.APP_NAME) \
          -o jsonpath='{.spec.template.spec.containers[0].image}'

        echo ""
        echo ""
        echo "Restarting $(params.APP_NAME) deployment..."

        oc rollout restart deployment/$(params.APP_NAME)

        echo ""
        echo "Waiting for rollout..."

        oc rollout status deployment/$(params.APP_NAME) \
          --timeout=300s

        echo ""
        echo "========================================"
        echo "Deployment Successful"
        echo "========================================"

        echo ""
        echo "Deployment:"
        oc get deployment $(params.APP_NAME)

        echo ""
        echo "Pods:"
        oc get pods -l app=$(params.APP_NAME)