apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  generateName: ui-pipeline-run-

spec:

  pipelineRef:
    name: ui-pipeline

  params:

    - name: repo-url
      value: https://github.com/amir35/tutorial-system.git

    - name: revision
      value: feature/openshift

  workspaces:

    - name: shared-workspace

      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce

          storageClassName: gp3

          resources:
            requests:
              storage: 1Gi