apiVersion: tekton.dev/v1
kind: Pipeline

metadata:
  name: ui-pipeline

spec:

  params:

    - name: repo-url
      type: string

    - name: revision
      type: string
      default: feature/openshift

  workspaces:

    - name: shared-workspace

  tasks:

    # =========================================
    # 1. Git Clone
    # =========================================

    - name: clone-repository

      taskRef:
        name: git-clone-task

      params:

        - name: repo-url
          value: $(params.repo-url)

        - name: revision
          value: $(params.revision)

      workspaces:

        - name: source
          workspace: shared-workspace


    # =========================================
    # 2. UI Image Build
    # =========================================

    - name: image-build

      runAfter:
        - clone-repository

      taskRef:
        name: image-build-task

      params:

        - name: APP_NAME
          value: tutorial-ui

      workspaces:

        - name: source
          workspace: shared-workspace


    # =========================================
    # 3. Deploy UI
    # =========================================

    - name: deploy

      runAfter:
        - image-build

      taskRef:
        name: deploy-task

      params:

        - name: APP_NAME
          value: tutorial-ui