apiVersion: build.openshift.io/v1
kind: BuildConfig

metadata:
  name: tutorial-ui

spec:

  source:
    git:
      uri: https://github.com/amir35/tutorial-system.git
      ref: feature/openshift
    type: Git

    contextDir: tutorial-ui

  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile

  output:
    to:
      kind: ImageStreamTag
      name: tutorial-ui:latest

  triggers:
    - type: ConfigChange
