spring.application.name=tutorial-service

#Since we are using Spring Boot inside docker container, we need to use host.docker.internal instead of localhost.
#We can also use IP from Ipconfig but it keeps on changing, so we need to update it everytime.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#for local connect, use localhost. For docker, connect using host.docker.internal

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true