pipeline {

    agent any

    parameters {

        booleanParam(
            name: 'DEPLOY',
            defaultValue: true,
            description: 'Deploy to Kubernetes?'
        )

        string(
            name: 'DOCKER_TAG',
            defaultValue: '',
            description: 'Leave empty to use BUILD_NUMBER'
        )
    }

    tools {
        maven 'Maven-3.9'
    }

    environment {
        IMAGE_NAME = 'amirdocker2204/tutorial-service'
        IMAGE_TAG = "${params.DOCKER_TAG ?: BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'feature/jenkins',
                    url: 'https://github.com/amir35/tutorial-system.git'
            }
        }

        stage('Build') {
            steps {
                dir('tutorial-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Print Variables') {
            steps {
                script {
                    echo "DEPLOY     : ${params.DEPLOY}"
                    echo "DOCKER_TAG : ${IMAGE_TAG}"
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('tutorial-service') {
                    sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push $IMAGE_NAME:$IMAGE_TAG'
            }
        }

        stage('Deploy to Kubernetes') {

            when {
                expression { params.DEPLOY }
            }

            steps {

                withCredentials([
                    file(
                        credentialsId: 'kubeconfig',
                        variable: 'KUBECONFIG'
                    )
                ]) {

                    sh '''
                        kubectl set image deployment/tutorial-service \
                        tutorial-service=$IMAGE_NAME:$IMAGE_TAG

                        kubectl rollout status deployment/tutorial-service
                    '''
                }
            }
        }
    }

    post {

        success {
            echo 'Pipeline Completed Successfully'
        }

        failure {
            echo 'Pipeline Failed'
        }

        always {
            cleanWs()
        }
    }
}